version: '3.8'

services:
  lean-lite:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lean-lite
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - BROKER_TYPE=alpaca
      - DATA_PROVIDER=alpaca
      - LOG_LEVEL=INFO
    volumes:
      - ../strategies:/app/strategies
      - ../logs:/app/logs
    restart: unless-stopped
    networks:
      - lean-network

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    container_name: lean-lite-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lean-network

volumes:
  redis_data:

networks:
  lean-network:
    driver: bridge 